services:
  - type: web
    name: mern-client
    runtime: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_BASE_URL
        value: https://mern-api.onrender.com/api
